version: "3"
services:
  redis-master1:
    image: redis:5.0 # 基础镜像
    container_name: node1 # 容器名称
    working_dir: /config # 切换工作目录
    restart: always
    environment: # 环境变量
      - PORT=6391 # 会使用config/nodes-${PORT}.conf这个配置文件
    ports: # 映射端口，对外提供服务
      - 6391:6391 # redis的服务端口
      - 16391:16391 # redis集群监控端口
    networks:
      redis:
        ipv4_address: 172.22.2.7
    stdin_open: true # 标准输入打开
    tty: true # 后台运行不退出
    #network_mode: host # 使用host模式
    privileged: true # 拥有容器内命令执行的权限
    volumes:
      - /usr/local/redis-cluster/config:/config #配置文件目录映射到宿主机
      - /usr/local/redis-cluster/data:/data
    entrypoint: # 设置服务默认的启动程序
      - /bin/bash
      - redis.sh
  redis-master2:
    image: redis:5.0
    working_dir: /config
    container_name: node2
    restart: always
    environment:
      - PORT=6392
    ports:
      - 6392:6392
      - 16392:16392
    networks:
      redis:
        ipv4_address: 172.22.2.8
    stdin_open: true
    #network_mode: host
    tty: true
    privileged: true
    volumes:
      - /usr/local/redis-cluster/config:/config
      - /usr/local/redis-cluster/data:/data
    entrypoint:
      - /bin/bash
      - redis.sh
  redis-master3:
    image: redis:5.0
    container_name: node3
    restart: always
    working_dir: /config
    environment:
      - PORT=6393
    ports:
      - 6393:6393
      - 16393:16393
    networks:
      redis:
        ipv4_address: 172.22.2.9
    stdin_open: true
    #network_mode: host
    tty: true
    privileged: true
    volumes:
      - /usr/local/redis-cluster/config:/config
      - /usr/local/redis-cluster/data:/data
    entrypoint:
      - /bin/bash
      - redis.sh
  redis-slave1:
    image: redis:5.0
    container_name: node4
    restart: always
    working_dir: /config
    environment:
      - PORT=6394
    ports:
      - 6394:6394
      - 16394:16394
    networks:
      redis:
        ipv4_address: 172.22.2.10
    stdin_open: true
    #network_mode: host
    tty: true
    privileged: true
    volumes:
      - /usr/local/redis-cluster/config:/config
      - /usr/local/redis-cluster/data:/data
    entrypoint:
      - /bin/bash
      - redis.sh
  redis-slave2:
    image: redis:5.0
    working_dir: /config
    container_name: node5
    restart: always
    environment:
      - PORT=6395
    ports:
      - 6395:6395
      - 16395:16395
    networks:
      redis:
        ipv4_address: 172.22.2.11
    stdin_open: true
    #network_mode: host
    tty: true
    privileged: true
    volumes:
      - /usr/local/redis-cluster/config:/config
      - /usr/local/redis-cluster/data:/data
    entrypoint:
      - /bin/bash
      - redis.sh
  redis-slave3:
    image: redis:5.0
    container_name: node6
    restart: always
    working_dir: /config
    environment:
      - PORT=6396
    ports:
      - 6396:6396
      - 16396:16396
    networks:
      redis:
        ipv4_address: 172.22.2.12
    stdin_open: true
    #network_mode: host
    tty: true
    privileged: true
    volumes:
      - /usr/local/redis-cluster/config:/config
      - /usr/local/redis-cluster/data:/data
    entrypoint:
      - /bin/bash
      - redis.sh

# 网桥redis -> 方便相互通讯
networks:
  redis:
    ipam:
      driver: default
      config:
        - subnet: "172.22.2.0/24"

