version: '3'
services:
  mysql:
    image: mysql:5.7.11
    restart: always
    container_name: mysql5.7.11
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=256M;
    ports:
      - 3307:3307
    volumes:
      - /usr/local/mysql5.7/data:/var/lib/mysql
      - /usr/local/mysql5.7/config/my.cnf:/etc/mysql/my.cnf
