/*
 Navicat Premium Data Transfer

 Source Server         : 172.25.21.29资管研发环境
 Source Server Type    : MySQL
 Source Server Version : 50717
 Source Host           : 172.25.21.29:3306
 Source Schema         : md_device_mgr

 Target Server Type    : MySQL
 Target Server Version : 50717
 File Encoding         : 65001

 Date: 18/11/2021 10:23:34
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for DM_STD_TABLE
-- ----------------------------
DROP TABLE IF EXISTS `DM_STD_TABLE`;
CREATE TABLE `DM_STD_TABLE` (
  `TABLE_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '表ID',
  `TABLE_CODE` varchar(100) DEFAULT NULL COMMENT '表名',
  `TABLE_NAME` varchar(100) DEFAULT NULL COMMENT '中文名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `AUDIT_TABLE_CODE` varchar(100) DEFAULT NULL COMMENT '审核表(申请表)',
  `USE_TYPE` int(11) DEFAULT NULL COMMENT '使用场景',
  `CODE_COLUMN` varchar(100) DEFAULT NULL COMMENT '唯一标识字段',
  `NAME_COLUMN` varchar(50) DEFAULT NULL COMMENT '名称字段标志',
  `SEARCH_COLUMN` varchar(500) DEFAULT NULL COMMENT '搜索字段',
  `TABLE_ALIAS` varchar(30) DEFAULT NULL COMMENT '表别名',
  `DM_COLUMN` varchar(500) DEFAULT NULL COMMENT '质量清单字段',
  `SHARE_CONF_TABLE` varchar(40) DEFAULT NULL COMMENT '共享配置表',
  `IS_PHYSICAL` int(11) DEFAULT NULL COMMENT '是否创建1:是,0:否',
  `CAT_CODE` varchar(10) DEFAULT NULL COMMENT '目录字段',
  `PARENT_ID` int(11) DEFAULT NULL COMMENT '父设备ID',
  `PARENT_CODE_COLUMN` varchar(100) DEFAULT NULL COMMENT '父设备编码',
  `RELATE_COLUMN` varchar(512) DEFAULT NULL COMMENT '关联字段',
  PRIMARY KEY (`TABLE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8 COMMENT='标准表模型';

-- ----------------------------
-- Records of DM_STD_TABLE
-- ----------------------------
BEGIN;
INSERT INTO `DM_STD_TABLE` VALUES (1, 'OMOF_CAMERA_INFO', '摄像机', '2020-06-18 15:05:43', 'OMOF_CAMERA_INFO_AUDIT', 1, 'SBBM', 'SBMC', 'SBBM,SBMC,LGBH,IPV4', 'camera', 'SBMC,JKDWLX,XZQH,JSDW', 'SHARE_CONF_DEVICE_CAMERA', 1, 'XZQH', NULL, NULL, '[{\"relateCode\":\"LGBH\",\"relateTableCode\":\"OMOF_ROD_BODY_INFO\",\"relateTableCodeColumn\":\"LGBH\",\"relateFieldCode\":\"GLSXJBM\"}]');
INSERT INTO `DM_STD_TABLE` VALUES (2, 'OMOF_VEHICLE_BARRIER_INFO', '车辆卡口', '2020-06-18 16:01:56', 'OMOF_VEHICLE_BARRIER_INFO_AUDIT', 1, 'KKBH', 'KKMC', 'KKBH,KKMC', 'kakou', 'KKYYLX,XZQH,GLDW', 'SHARE_CONF_DEVICE_KAKOU', 1, 'XZQH', NULL, NULL, '[{\"relateCode\":\"LGBH\",\"relateTableCode\":\"OMOF_ROD_BODY_INFO\",\"relateTableCodeColumn\":\"LGBH\",\"relateFieldCode\":\"GLCLKKGH\"}]');
INSERT INTO `DM_STD_TABLE` VALUES (3, 'OMOF_LANE_INFO', '车道信息', '2020-06-18 16:47:54', 'OMOF_LANE_INFO_AUDIT', 1, 'KKBH,CDBH,SXJSBBM', 'CDBH', 'KKBH,CDBH', 'lane', 'CDBH,KKBH,SXJSBBM,XZQH', 'SHARE_CONF_DEVICE_LANE', 1, 'XZQH', 2, 'KKBH', NULL);
INSERT INTO `DM_STD_TABLE` VALUES (4, 'OMOF_DOORACCESS_INFO', '门禁设备', '2020-06-18 16:54:45', 'OMOF_DOORACCESS_INFO_AUDIT', 1, 'MJBM', 'MJMC', 'MJBM,MJMC,IPV4', 'door', 'XZQH', 'SHARE_CONF_DEVICE_DOOR', 1, 'XZQH', NULL, NULL, NULL);
INSERT INTO `DM_STD_TABLE` VALUES (5, 'OMOF_WIFI_INFO', 'WIFI热点', '2020-06-18 17:00:22', 'OMOF_WIFI_INFO_AUDIT', 1, 'RDBM', 'RDMC', 'RDBM,RDMC', 'wifi', 'XZQH', 'SHARE_CONF_DEVICE_WIFI', 1, 'XZQH', NULL, NULL, NULL);
INSERT INTO `DM_STD_TABLE` VALUES (6, 'OMOF_EFENSE_INFO', '电子围栏', '2020-06-18 17:03:26', 'OMOF_EFENSE_INFO_AUDIT', 1, 'DWBM', 'DWMC', 'DWBM,DWMC', 'efense', 'XZQH', 'SHARE_CONF_DEVICE_EFENSE', 1, 'XZQH', NULL, NULL, NULL);
INSERT INTO `DM_STD_TABLE` VALUES (7, 'OMOF_STORAGE_INFO', '存储设备', '2020-06-18 17:06:29', 'OMOF_STORAGE_INFO_AUDIT', 1, 'SBBM', 'SBMC', 'SBBM,SBMC', 'storage', 'XZQH', 'SHARE_CONF_DEVICE_STORAGE', 1, 'XZQH', NULL, NULL, NULL);
INSERT INTO `DM_STD_TABLE` VALUES (8, 'OMOF_ENCODER_INFO', '编码器', '2020-06-18 17:09:07', 'OMOF_ENCODER_INFO_AUDIT', 1, 'SBBM', 'SBMC', 'SBBM,SBMC', 'encoder', 'XZQH', 'SHARE_CONF_DEVICE_ENCODER', 1, 'XZQH', NULL, NULL, NULL);
INSERT INTO `DM_STD_TABLE` VALUES (9, 'OMOF_PARKINGLOG_INFO', '停车场', '2021-03-11 20:12:48', 'OMOF_PARKINGLOG_INFO_AUDIT', 1, 'TCCBH', 'TCCMC', 'TCCBH,TCCMC', 'ParkingLot', NULL, 'SHARE_CONF_DEVICE_PARKINGLOT', 1, 'XZQH', NULL, NULL, NULL);
INSERT INTO `DM_STD_TABLE` VALUES (10, 'OMOF_ELECFENSEDETECT_INFO', '电围嗅探', '2021-05-08 15:12:48', 'OMOF_ELECFENSEDETECT_INFO_AUDIT', 1, 'SBBM', 'SBMC', 'SBBM,SBMC', 'ElecfenseDetect', NULL, 'SHARE_CONF_DEVICE_ELECFENSEDETECT', 1, NULL, NULL, NULL, '[{\"relateCode\":\"LGBH\",\"relateTableCode\":\"OMOF_ROD_BODY_INFO\",\"relateTableCodeColumn\":\"LGBH\",\"relateFieldCode\":\"GLDWXTBM\"}]');
INSERT INTO `DM_STD_TABLE` VALUES (12, 'TEST', '测试', '2021-08-02 09:40:29', 'TEST_AUDIT', 1, NULL, NULL, NULL, 'TSET', NULL, 'SHARE_CONF_DEVICE_TSET', 0, NULL, NULL, NULL, NULL);
INSERT INTO `DM_STD_TABLE` VALUES (13, 'OMOF_DOOR_STAGE_INFO', '驿站门禁', '2021-08-10 17:43:23', 'OMOF_DOOR_STAGE_INFO_AUDIT', 1, 'MJBM', 'MJMC', 'MJBM,MJMC', 'stageDoor', NULL, 'SHARE_CONF_DEVICE_STAGEDOOR', 0, 'XZQH', NULL, NULL, NULL);
INSERT INTO `DM_STD_TABLE` VALUES (15, 'OMOF_TESTDEVICE_INFO', '测试档案建档', '2021-10-25 10:59:30', 'OMOF_TESTDEVICE_INFO_AUDIT', 1, 'SBBM', 'SBMC', 'SBBM,SBMC', 'testDevice', NULL, 'SHARE_CONF_DEVICE_TESTDEVICE', 0, 'XZQH', NULL, NULL, NULL);
INSERT INTO `DM_STD_TABLE` VALUES (17, 'OMOF_PERSON_INFO', '人员档案', '2021-10-27 11:02:16', 'OMOF_PERSON_INFO_AUDIT', 1, 'IDNUMBER', '', '', 'fileinfo', '', 'SHARE_CONF_DEVICE_FILEINFO', 1, '', NULL, NULL, NULL);
INSERT INTO `DM_STD_TABLE` VALUES (21, 'OMOF_DECODER_INFO', '解码器', '2021-09-13 10:48:01', 'OMOF_DECODER_INFO_AUDIT', 1, 'SBBM', 'SBMC', 'SBBM,SBMC', 'decoder', NULL, 'SHARE_CONF_DEVICE_DECODER', 1, 'XZQH', NULL, NULL, NULL);
INSERT INTO `DM_STD_TABLE` VALUES (22, 'OMOF_CAMERA_INFO_T', '测试档案建档1', '2021-11-02 11:57:01', 'OMOF_CAMERA_INFO_T_AUDIT', 1, 'XZQH', NULL, NULL, 'testadd', NULL, 'SHARE_CONF_DEVICE_TESTADD', 1, NULL, NULL, NULL, NULL);
INSERT INTO `DM_STD_TABLE` VALUES (23, 'TEST_CESHI', '测试', '2021-11-11 16:19:40', 'TEST_CESHI_AUDIT', 1, 'XZQH', NULL, NULL, 'CESHI', NULL, 'SHARE_CONF_DEVICE_CESHI', 1, NULL, NULL, NULL, NULL);
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
