/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 50711
 Source Host           : localhost:3306
 Source Schema         : yangjian_metric

 Target Server Type    : MySQL
 Target Server Version : 50711
 File Encoding         : 65001

 Date: 18/11/2021 13:49:28
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for source
-- ----------------------------
DROP TABLE IF EXISTS `source`;
CREATE TABLE `source` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `source_group_id` bigint(20) NOT NULL COMMENT '数据源分类',
  `sign` varchar(50) NOT NULL COMMENT '数据源唯一标识，3种用途\r\n1.可用于绑定来源数据与source配置，如实时计算的数据推送给监控时，url后就会带上该sign；\r\n2.用于monitor监控配置，如kafka延迟配置时，会向monitor表中增加数据，此时的sourceId就是用sign查询source表获取的；\r\n3.作为数据源转发到kafka的topic；',
  `name` varchar(50) NOT NULL COMMENT '数据源名称，如kafka延迟、rabbitmq延迟、kafka请求量及延迟、mysql请求量及延迟、sql拨测、用例拨测.....',
  `partition_number` int(11) NOT NULL DEFAULT '10' COMMENT '分区个数，值仅允许增加，不可减少',
  `replication_factor` int(11) NOT NULL DEFAULT '1' COMMENT '每个分区冗余个数，1为不冗余',
  `hash_key` varchar(50) DEFAULT NULL COMMENT '发送数据到kafka时用的hash key的字段名，获取字段名对应的value作为hash key，用于在需要保证顺序的场景中使用，多个key使用英文逗号分隔',
  `key_type_mapping` varchar(1024) DEFAULT NULL COMMENT '每个字段对应的类型映射（json格式）如：{"serviceName":"String"}',
  `last_input_time` datetime DEFAULT NULL COMMENT '数据源事件进入的最新时间（可定时更新，如1天更新一次），用于监控数据源长时间无数据时发出告警',
  `remark` varchar(255) DEFAULT NULL COMMENT '数据源描述',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_``source_group_id``` (`source_group_id`,`name`) USING BTREE,
  UNIQUE KEY `uniq_``sign``` (`sign`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='监控数据源，定义了所有统计数据的数据源信息';

-- ----------------------------
-- Records of source
-- ----------------------------
BEGIN;
INSERT INTO `source` VALUES (1, 3, 'TM-JVM', 'JVM监控监控', 3, 1, 'serviceName', '{\"cpu\":\"Double\",\"oldgen\":\"Long\",\"codeCache\":\"Long\",\"eden\":\"Long\",\"survivor\":\"Long\",\"permgen\":\"Long\",\"metaspace\":\"Long\",\"mappedCache\":\"Long\",\"directMemory\":\"Long\",\"heap\":\"Long\",\"nonHeap\":\"Long\",\"memoryTotal\":\"Double\",\"classLoaded\":\"Long\",\"classUnloaded\":\"Long\",\"classTotal\":\"Long\",\"youngGcCount\":\"Long\",\"fullGcTime\":\"Long\",\"fullGcCount\":\"Long\",\"youngGcTime\":\"Long\",\"avgYoungGcTime\":\"Double\",\"threadRunnable\":\"Long\",\"threadBlocked\":\"Long\",\"threadWaiting\":\"Long\",\"threadDaemon\":\"Long\",\"threadPeak\":\"Long\",\"threadTotalStarted\":\"Long\",\"threadActive\":\"Long\",\"threadTimedWaiting\":\"Long\",\"threadTerminated\":\"Long\",\"threadNews\":\"Long\",\"mappedBufferPoolCount\":\"Long\",\"mappedBufferPoolMemoryCapacity\":\"Long\",\"mappedBufferPoolMemoryUsed\":\"Long\",\"directBufferPoolCount\":\"Long\",\"directBufferPoolMemoryCapacity\":\"Long\",\"directBufferPoolMemoryUsed\":\"Long\"}', NULL, '', '2020-12-01 14:01:09', '2020-12-15 11:19:11');
INSERT INTO `source` VALUES (2, 1, 'TM-METHOD', '方法QPS、RT', 3, 1, 'serviceName', '{\"errorTotal\":\"Double\",\"num\":\"Double\",\"rtMin\":\"Double\",\"rtMax\":\"Double\",\"rtAvg\":\"Double\",\"sign\":\"Unicode\"}', NULL, NULL, '2020-12-16 15:11:25', '2021-02-23 17:17:42');
INSERT INTO `source` VALUES (4, 3, 'TM-SERVICE-STATUS', '服务启动关闭监控测试', 1, 1, 'serviceName', NULL, NULL, '', '2020-11-23 13:50:06', '2020-11-25 15:35:17');
INSERT INTO `source` VALUES (5, 3, 'TM_YANGJIAN', '杨戬监控启动关闭', 3, 1, 'serviceName', NULL, '2020-11-25 15:50:08', NULL, '2020-11-25 15:50:11', '2020-11-25 15:50:13');
INSERT INTO `source` VALUES (7, 4, 'TM-KAFKA', 'kafka监控', 10, 1, 'kafkaSource', NULL, NULL, NULL, '2020-12-15 11:11:17', '2020-12-15 11:11:41');
INSERT INTO `source` VALUES (11, 3, 'TM-JVM-THREAD', 'JVM监控-线程监控', 3, 1, 'serviceName', '{\"cpu\":\"Double\",\"oldgen\":\"Long\",\"codeCache\":\"Long\",\"eden\":\"Long\",\"survivor\":\"Long\",\"permgen\":\"Long\",\"metaspace\":\"Long\",\"mappedCache\":\"Long\",\"directMemory\":\"Long\",\"heap\":\"Long\",\"nonHeap\":\"Long\",\"memoryTotal\":\"Double\",\"classLoaded\":\"Long\",\"classUnloaded\":\"Long\",\"classTotal\":\"Long\",\"youngGcCount\":\"Long\",\"fullGcTime\":\"Long\",\"fullGcCount\":\"Long\",\"youngGcTime\":\"Long\",\"avgYoungGcTime\":\"Double\",\"threadRunnable\":\"Long\",\"threadBlocked\":\"Long\",\"threadWaiting\":\"Long\",\"threadDaemon\":\"Long\",\"threadPeak\":\"Long\",\"threadTotalStarted\":\"Long\",\"threadActive\":\"Long\",\"threadTimedWaiting\":\"Long\",\"threadTerminated\":\"Long\",\"threadNews\":\"Long\",\"mappedBufferPoolCount\":\"Long\",\"mappedBufferPoolMemoryCapacity\":\"Long\",\"mappedBufferPoolMemoryUsed\":\"Long\",\"directBufferPoolCount\":\"Long\",\"directBufferPoolMemoryCapacity\":\"Long\",\"directBufferPoolMemoryUsed\":\"Long\",\"sysMemTotal\":\"Long\",\"memoryUsagePercent\":\"Double\"}', NULL, '', '2020-12-01 14:01:09', '2021-01-19 13:20:02');
INSERT INTO `source` VALUES (12, 3, 'TM-JVM-GC', 'JVM监控-gc监控', 3, 1, 'serviceName', '{\"cpu\":\"Double\",\"oldgen\":\"Long\",\"codeCache\":\"Long\",\"eden\":\"Long\",\"survivor\":\"Long\",\"permgen\":\"Long\",\"metaspace\":\"Long\",\"mappedCache\":\"Long\",\"directMemory\":\"Long\",\"heap\":\"Long\",\"nonHeap\":\"Long\",\"memoryTotal\":\"Double\",\"classLoaded\":\"Long\",\"classUnloaded\":\"Long\",\"classTotal\":\"Long\",\"youngGcCount\":\"Long\",\"fullGcTime\":\"Long\",\"fullGcCount\":\"Long\",\"youngGcTime\":\"Long\",\"avgYoungGcTime\":\"Double\",\"threadRunnable\":\"Long\",\"threadBlocked\":\"Long\",\"threadWaiting\":\"Long\",\"threadDaemon\":\"Long\",\"threadPeak\":\"Long\",\"threadTotalStarted\":\"Long\",\"threadActive\":\"Long\",\"threadTimedWaiting\":\"Long\",\"threadTerminated\":\"Long\",\"threadNews\":\"Long\",\"mappedBufferPoolCount\":\"Long\",\"mappedBufferPoolMemoryCapacity\":\"Long\",\"mappedBufferPoolMemoryUsed\":\"Long\",\"directBufferPoolCount\":\"Long\",\"directBufferPoolMemoryCapacity\":\"Long\",\"directBufferPoolMemoryUsed\":\"Long\",\"sysMemTotal\":\"Long\",\"memoryUsagePercent\":\"Double\"}', NULL, '', '2020-12-01 14:01:09', '2021-01-19 13:20:00');
INSERT INTO `source` VALUES (13, 3, 'TM-JVM-CPU-MEMORY', 'JVM监控-cpu和内存监控', 3, 1, 'serviceName', '{\"cpu\":\"Double\",\"oldgen\":\"Long\",\"codeCache\":\"Long\",\"eden\":\"Long\",\"survivor\":\"Long\",\"permgen\":\"Long\",\"metaspace\":\"Long\",\"mappedCache\":\"Long\",\"directMemory\":\"Long\",\"heap\":\"Long\",\"nonHeap\":\"Long\",\"memoryTotal\":\"Double\",\"classLoaded\":\"Long\",\"classUnloaded\":\"Long\",\"classTotal\":\"Long\",\"youngGcCount\":\"Long\",\"fullGcTime\":\"Long\",\"fullGcCount\":\"Long\",\"youngGcTime\":\"Long\",\"avgYoungGcTime\":\"Double\",\"threadRunnable\":\"Long\",\"threadBlocked\":\"Long\",\"threadWaiting\":\"Long\",\"threadDaemon\":\"Long\",\"threadPeak\":\"Long\",\"threadTotalStarted\":\"Long\",\"threadActive\":\"Long\",\"threadTimedWaiting\":\"Long\",\"threadTerminated\":\"Long\",\"threadNews\":\"Long\",\"mappedBufferPoolCount\":\"Long\",\"mappedBufferPoolMemoryCapacity\":\"Long\",\"mappedBufferPoolMemoryUsed\":\"Long\",\"directBufferPoolCount\":\"Long\",\"directBufferPoolMemoryCapacity\":\"Long\",\"directBufferPoolMemoryUsed\":\"Long\",\"sysMemTotal\":\"Long\",\"memoryUsagePercent\":\"Double\"}', NULL, '', '2020-12-01 14:01:09', '2021-01-19 13:19:54');
INSERT INTO `source` VALUES (14, 3, 'TM-JVM-BUFFER-POOL', 'JVM监控-buffer_pool监控', 3, 1, 'serviceName', '{\"cpu\":\"Double\",\"oldgen\":\"Long\",\"codeCache\":\"Long\",\"eden\":\"Long\",\"survivor\":\"Long\",\"permgen\":\"Long\",\"metaspace\":\"Long\",\"mappedCache\":\"Long\",\"directMemory\":\"Long\",\"heap\":\"Long\",\"nonHeap\":\"Long\",\"memoryTotal\":\"Double\",\"classLoaded\":\"Long\",\"classUnloaded\":\"Long\",\"classTotal\":\"Long\",\"youngGcCount\":\"Long\",\"fullGcTime\":\"Long\",\"fullGcCount\":\"Long\",\"youngGcTime\":\"Long\",\"avgYoungGcTime\":\"Double\",\"threadRunnable\":\"Long\",\"threadBlocked\":\"Long\",\"threadWaiting\":\"Long\",\"threadDaemon\":\"Long\",\"threadPeak\":\"Long\",\"threadTotalStarted\":\"Long\",\"threadActive\":\"Long\",\"threadTimedWaiting\":\"Long\",\"threadTerminated\":\"Long\",\"threadNews\":\"Long\",\"mappedBufferPoolCount\":\"Long\",\"mappedBufferPoolMemoryCapacity\":\"Long\",\"mappedBufferPoolMemoryUsed\":\"Long\",\"directBufferPoolCount\":\"Long\",\"directBufferPoolMemoryCapacity\":\"Long\",\"directBufferPoolMemoryUsed\":\"Long\",\"sysMemTotal\":\"Long\",\"memoryUsagePercent\":\"Double\"}', NULL, '', '2020-12-01 14:01:09', '2021-01-19 13:19:58');
INSERT INTO `source` VALUES (15, 3, 'TM-NGINX-DUAL-ACTIVE', '双活Nginx流量统计', 3, 1, 'domain', '{\"totalNum\":\"Long\",\"markMobileNum\":\"Long\",\"sessionIdNum\":\"Long\",\"responseTime\":\"Double\",\"minResponseTime\":\"Double\",\"maxResponseTime\":\"Double\",\"avgResponseTime\":\"Double\",\"uniqMobileNum\":\"Long\"}', NULL, '', '2020-12-01 14:01:09', '2021-01-29 11:04:41');
INSERT INTO `source` VALUES (16, 3, 'TM-NGINX-MONITOR', 'Nginx通用指标维度统计', 3, 1, 'domain', '{\"totalNum\":\"Long\",\"code2xx\":\"Long\",\"code4xx\":\"Long\",\"code5xx\":\"Long\",\"minResponseTime\":\"Double\",\"maxResponseTime\":\"Double\",\"avgResponseTime\":\"Double\"}', NULL, '', '2020-12-01 14:01:09', '2021-02-02 12:48:02');
INSERT INTO `source` VALUES (17, 3, 'TM-NGINX-STATS-MONITOR', 'Nginx通用统计按域名每分钟', 3, 1, 'domain', '{\"totalNum\":\"Long\",\"code2xx\":\"Long\",\"code4xx\":\"Long\",\"code5xx\":\"Long\",\"minResponseTime\":\"Double\",\"maxResponseTime\":\"Double\",\"avgResponseTime\":\"Double\"}', '2021-01-28 15:28:49', NULL, '2021-01-28 15:28:53', '2021-02-02 12:48:08');
INSERT INTO `source` VALUES (18, 3, 'TM-DIAL-TEST-MONITOR', '接口拨测数据', 3, 1, 'taskName', NULL, '2021-02-20 18:00:12', NULL, '2021-02-20 18:00:12', '2021-02-20 18:00:12');
INSERT INTO `source` VALUES (19, 5, 'TM-COMPASS-CPU', '容器云监控-cpu监控', 3, 1, 'pod', '{\"cpu\":\"Double\",\"oldgen\":\"Long\",\"codeCache\":\"Long\",\"eden\":\"Long\",\"survivor\":\"Long\",\"permgen\":\"Long\",\"metaspace\":\"Long\",\"mappedCache\":\"Long\",\"directMemory\":\"Long\",\"heap\":\"Long\",\"nonHeap\":\"Long\",\"memoryTotal\":\"Double\",\"classLoaded\":\"Long\",\"classUnloaded\":\"Long\",\"classTotal\":\"Long\",\"youngGcCount\":\"Long\",\"fullGcTime\":\"Long\",\"fullGcCount\":\"Long\",\"youngGcTime\":\"Long\",\"avgYoungGcTime\":\"Double\",\"threadRunnable\":\"Long\",\"threadBlocked\":\"Long\",\"threadWaiting\":\"Long\",\"threadDaemon\":\"Long\",\"threadPeak\":\"Long\",\"threadTotalStarted\":\"Long\",\"threadActive\":\"Long\",\"threadTimedWaiting\":\"Long\",\"threadTerminated\":\"Long\",\"threadNews\":\"Long\",\"mappedBufferPoolCount\":\"Long\",\"mappedBufferPoolMemoryCapacity\":\"Long\",\"mappedBufferPoolMemoryUsed\":\"Long\",\"directBufferPoolCount\":\"Long\",\"directBufferPoolMemoryCapacity\":\"Long\",\"directBufferPoolMemoryUsed\":\"Long\",\"usedValue\":\"Double\",\"availableValue\":\"Double\",\"cpuValue\":\"Double\",\"memValue\":\"Double\",\"receiveValue\":\"Double\",\"transmitValue\":\"Double\"}', '2021-03-26 16:19:30', NULL, '2021-03-26 16:19:21', '2021-03-29 19:05:46');
INSERT INTO `source` VALUES (20, 5, 'TM-COMPASS-MEMORY', '容器云监控-内存监控', 3, 1, 'pod', '{\"cpu\":\"Double\",\"oldgen\":\"Long\",\"codeCache\":\"Long\",\"eden\":\"Long\",\"survivor\":\"Long\",\"permgen\":\"Long\",\"metaspace\":\"Long\",\"mappedCache\":\"Long\",\"directMemory\":\"Long\",\"heap\":\"Long\",\"nonHeap\":\"Long\",\"memoryTotal\":\"Double\",\"classLoaded\":\"Long\",\"classUnloaded\":\"Long\",\"classTotal\":\"Long\",\"youngGcCount\":\"Long\",\"fullGcTime\":\"Long\",\"fullGcCount\":\"Long\",\"youngGcTime\":\"Long\",\"avgYoungGcTime\":\"Double\",\"threadRunnable\":\"Long\",\"threadBlocked\":\"Long\",\"threadWaiting\":\"Long\",\"threadDaemon\":\"Long\",\"threadPeak\":\"Long\",\"threadTotalStarted\":\"Long\",\"threadActive\":\"Long\",\"threadTimedWaiting\":\"Long\",\"threadTerminated\":\"Long\",\"threadNews\":\"Long\",\"mappedBufferPoolCount\":\"Long\",\"mappedBufferPoolMemoryCapacity\":\"Long\",\"mappedBufferPoolMemoryUsed\":\"Long\",\"directBufferPoolCount\":\"Long\",\"directBufferPoolMemoryCapacity\":\"Long\",\"directBufferPoolMemoryUsed\":\"Long\",\"usedValue\":\"Double\",\"availableValue\":\"Double\",\"cpuValue\":\"Double\",\"memValue\":\"Double\",\"receiveValue\":\"Double\",\"transmitValue\":\"Double\"}', '2021-03-26 16:20:37', NULL, '2021-03-26 16:20:39', '2021-03-29 19:05:48');
INSERT INTO `source` VALUES (21, 5, 'TM-COMPASS-UPLOAD', '容器云监控-上传带宽监控', 3, 1, 'pod', '{\"cpu\":\"Double\",\"oldgen\":\"Long\",\"codeCache\":\"Long\",\"eden\":\"Long\",\"survivor\":\"Long\",\"permgen\":\"Long\",\"metaspace\":\"Long\",\"mappedCache\":\"Long\",\"directMemory\":\"Long\",\"heap\":\"Long\",\"nonHeap\":\"Long\",\"memoryTotal\":\"Double\",\"classLoaded\":\"Long\",\"classUnloaded\":\"Long\",\"classTotal\":\"Long\",\"youngGcCount\":\"Long\",\"fullGcTime\":\"Long\",\"fullGcCount\":\"Long\",\"youngGcTime\":\"Long\",\"avgYoungGcTime\":\"Double\",\"threadRunnable\":\"Long\",\"threadBlocked\":\"Long\",\"threadWaiting\":\"Long\",\"threadDaemon\":\"Long\",\"threadPeak\":\"Long\",\"threadTotalStarted\":\"Long\",\"threadActive\":\"Long\",\"threadTimedWaiting\":\"Long\",\"threadTerminated\":\"Long\",\"threadNews\":\"Long\",\"mappedBufferPoolCount\":\"Long\",\"mappedBufferPoolMemoryCapacity\":\"Long\",\"mappedBufferPoolMemoryUsed\":\"Long\",\"directBufferPoolCount\":\"Long\",\"directBufferPoolMemoryCapacity\":\"Long\",\"directBufferPoolMemoryUsed\":\"Long\",\"usedValue\":\"Double\",\"availableValue\":\"Double\",\"cpuValue\":\"Double\",\"memValue\":\"Double\",\"receiveValue\":\"Double\",\"transmitValue\":\"Double\"}', '2021-03-26 16:22:44', NULL, '2021-03-26 16:22:47', '2021-04-30 18:19:52');
INSERT INTO `source` VALUES (22, 5, 'TM-COMPASS-DISK', '容器云监控-disk监控', 3, 1, 'pod', '{\"cpu\":\"Double\",\"oldgen\":\"Long\",\"codeCache\":\"Long\",\"eden\":\"Long\",\"survivor\":\"Long\",\"permgen\":\"Long\",\"metaspace\":\"Long\",\"mappedCache\":\"Long\",\"directMemory\":\"Long\",\"heap\":\"Long\",\"nonHeap\":\"Long\",\"memoryTotal\":\"Double\",\"classLoaded\":\"Long\",\"classUnloaded\":\"Long\",\"classTotal\":\"Long\",\"youngGcCount\":\"Long\",\"fullGcTime\":\"Long\",\"fullGcCount\":\"Long\",\"youngGcTime\":\"Long\",\"avgYoungGcTime\":\"Double\",\"threadRunnable\":\"Long\",\"threadBlocked\":\"Long\",\"threadWaiting\":\"Long\",\"threadDaemon\":\"Long\",\"threadPeak\":\"Long\",\"threadTotalStarted\":\"Long\",\"threadActive\":\"Long\",\"threadTimedWaiting\":\"Long\",\"threadTerminated\":\"Long\",\"threadNews\":\"Long\",\"mappedBufferPoolCount\":\"Long\",\"mappedBufferPoolMemoryCapacity\":\"Long\",\"mappedBufferPoolMemoryUsed\":\"Long\",\"directBufferPoolCount\":\"Long\",\"directBufferPoolMemoryCapacity\":\"Long\",\"directBufferPoolMemoryUsed\":\"Long\",\"usedValue\":\"Double\",\"availableValue\":\"Double\",\"cpuValue\":\"Double\",\"memValue\":\"Double\",\"receiveValue\":\"Double\",\"transmitValue\":\"Double\"}', '2021-03-26 16:22:44', NULL, '2021-03-26 16:22:47', '2021-03-29 19:05:51');
INSERT INTO `source` VALUES (23, 5, 'TM-COMPASS-EVENT', '容器云监控-event监控', 3, 1, 'appName', '{\"cpu\":\"Double\",\"oldgen\":\"Long\",\"codeCache\":\"Long\",\"eden\":\"Long\",\"survivor\":\"Long\",\"permgen\":\"Long\",\"metaspace\":\"Long\",\"mappedCache\":\"Long\",\"directMemory\":\"Long\",\"heap\":\"Long\",\"nonHeap\":\"Long\",\"memoryTotal\":\"Double\",\"classLoaded\":\"Long\",\"classUnloaded\":\"Long\",\"classTotal\":\"Long\",\"youngGcCount\":\"Long\",\"fullGcTime\":\"Long\",\"fullGcCount\":\"Long\",\"youngGcTime\":\"Long\",\"avgYoungGcTime\":\"Double\",\"threadRunnable\":\"Long\",\"threadBlocked\":\"Long\",\"threadWaiting\":\"Long\",\"threadDaemon\":\"Long\",\"threadPeak\":\"Long\",\"threadTotalStarted\":\"Long\",\"threadActive\":\"Long\",\"threadTimedWaiting\":\"Long\",\"threadTerminated\":\"Long\",\"threadNews\":\"Long\",\"mappedBufferPoolCount\":\"Long\",\"mappedBufferPoolMemoryCapacity\":\"Long\",\"mappedBufferPoolMemoryUsed\":\"Long\",\"directBufferPoolCount\":\"Long\",\"directBufferPoolMemoryCapacity\":\"Long\",\"directBufferPoolMemoryUsed\":\"Long\",\"usedValue\":\"Double\",\"availableValue\":\"Double\",\"cpuValue\":\"Double\",\"memValue\":\"Double\",\"receiveValue\":\"Double\",\"transmitValue\":\"Double\"}', '2021-03-30 15:35:31', NULL, '2021-03-30 15:35:33', '2021-04-01 16:46:31');
INSERT INTO `source` VALUES (24, 5, 'TM-COMPASS-DOWNLOAD', '容器云监控-下载带宽监控', 3, 1, 'pod', '{\"cpu\":\"Double\",\"oldgen\":\"Long\",\"codeCache\":\"Long\",\"eden\":\"Long\",\"survivor\":\"Long\",\"permgen\":\"Long\",\"metaspace\":\"Long\",\"mappedCache\":\"Long\",\"directMemory\":\"Long\",\"heap\":\"Long\",\"nonHeap\":\"Long\",\"memoryTotal\":\"Double\",\"classLoaded\":\"Long\",\"classUnloaded\":\"Long\",\"classTotal\":\"Long\",\"youngGcCount\":\"Long\",\"fullGcTime\":\"Long\",\"fullGcCount\":\"Long\",\"youngGcTime\":\"Long\",\"avgYoungGcTime\":\"Double\",\"threadRunnable\":\"Long\",\"threadBlocked\":\"Long\",\"threadWaiting\":\"Long\",\"threadDaemon\":\"Long\",\"threadPeak\":\"Long\",\"threadTotalStarted\":\"Long\",\"threadActive\":\"Long\",\"threadTimedWaiting\":\"Long\",\"threadTerminated\":\"Long\",\"threadNews\":\"Long\",\"mappedBufferPoolCount\":\"Long\",\"mappedBufferPoolMemoryCapacity\":\"Long\",\"mappedBufferPoolMemoryUsed\":\"Long\",\"directBufferPoolCount\":\"Long\",\"directBufferPoolMemoryCapacity\":\"Long\",\"directBufferPoolMemoryUsed\":\"Long\",\"usedValue\":\"Double\",\"availableValue\":\"Double\",\"cpuValue\":\"Double\",\"memValue\":\"Double\",\"receiveValue\":\"Double\",\"transmitValue\":\"Double\"}', '2021-03-26 16:22:44', NULL, '2021-03-26 16:22:47', '2021-04-30 18:20:17');
INSERT INTO `source` VALUES (25, 5, 'TM-COMPASS-DISK-SUROLUS', '容器云监控-容器云DISK挂载PVC的磁盘剩余磁盘量', 3, 1, 'pod', '{\"cpu\":\"Double\",\"oldgen\":\"Long\",\"codeCache\":\"Long\",\"eden\":\"Long\",\"survivor\":\"Long\",\"permgen\":\"Long\",\"metaspace\":\"Long\",\"mappedCache\":\"Long\",\"directMemory\":\"Long\",\"heap\":\"Long\",\"nonHeap\":\"Long\",\"memoryTotal\":\"Double\",\"classLoaded\":\"Long\",\"classUnloaded\":\"Long\",\"classTotal\":\"Long\",\"youngGcCount\":\"Long\",\"fullGcTime\":\"Long\",\"fullGcCount\":\"Long\",\"youngGcTime\":\"Long\",\"avgYoungGcTime\":\"Double\",\"threadRunnable\":\"Long\",\"threadBlocked\":\"Long\",\"threadWaiting\":\"Long\",\"threadDaemon\":\"Long\",\"threadPeak\":\"Long\",\"threadTotalStarted\":\"Long\",\"threadActive\":\"Long\",\"threadTimedWaiting\":\"Long\",\"threadTerminated\":\"Long\",\"threadNews\":\"Long\",\"mappedBufferPoolCount\":\"Long\",\"mappedBufferPoolMemoryCapacity\":\"Long\",\"mappedBufferPoolMemoryUsed\":\"Long\",\"directBufferPoolCount\":\"Long\",\"directBufferPoolMemoryCapacity\":\"Long\",\"directBufferPoolMemoryUsed\":\"Long\",\"usedValue\":\"Double\",\"availableValue\":\"Double\",\"cpuValue\":\"Double\",\"memValue\":\"Double\",\"receiveValue\":\"Double\",\"transmitValue\":\"Double\"}', '2021-03-26 16:22:44', NULL, '2021-03-26 16:22:47', '2021-04-30 18:21:09');
INSERT INTO `source` VALUES (26, 1, 'TM-POOL', '连接池', 3, 1, 'serviceName', '{\"maxTotal\":\"Double\",\"activeCount\":\"Double\",\"sign\":\"Unicode\"}', NULL, NULL, '2020-12-16 15:11:25', '2021-05-25 18:12:38');
INSERT INTO `source` VALUES (28, 0, 'TM-APP-LOG', '应用日志监控', 3, 1, 'serviceName', '{}', NULL, NULL, '2021-06-16 16:14:13', '2021-06-16 16:16:08');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
