version: '3'
 
services: 
  canal-server: 
    image: canal/canal-server:latest
    container_name: canal-server
    ports: 
      - 11111:11111
    environment: 
      - canal.instance.mysql.slaveId=12
      - canal.auto.scan=false
      - canal.destinations=compose-canal
      - canal.instance.master.address=192.168.32.2:3306
      - canal.instance.dbUsername=canal
      - canal.instance.dbPassword=canal
      - canal.mq.topic=compose-canal
    volumes: 
      - /usr/local/canal/logs/:/admin/canal-server/logs/
      - /usr/local/canal/canal.properties:/home/admin/canal-server/conf/canal.properties



