version: '3'
services:
  mysql:
    image: mysql:8.0.16
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=512M;
    ports:
      - 3306:3306
    volumes:
      - /usr/local/mysql8/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /usr/local/mysql8/config/my.cnf:/etc/mysql/my.cnf
