version: "3"
services:
  seata-server:
    image: seataio/seata-server:1.3.0
    hostname: seata-server
    ports:
      - "8091:8091"
    environment:
      - SEATA_IP=192.168.32.2
      - SEATA_PORT=8091
      - STORE_MODE=db
    volumes:
      - "/usr/local/seata/registry.conf:/seata-server/resources/registry.conf"
      - "/usr/local/seata/logs:/root/logs/seata"
      - "/usr/local/seata/lib/mysql-connector-java-8.0.21.jar:/seata-server/libs/mysql-connector-java-8.0.21.jar"
networks:
  seatanet:
    driver: bridge


