version: '3.1'

networks:
  default:
    external:
      name: zknet
services:
  kafka1:
    image: wurstmeister/kafka
    restart: unless-stopped
    container_name: kafka1
    hostname: kafka1
    expose:
      - "9999"
    ports:
      - "9092:9092"
      - "9999:9999"
    external_links:
      - zoo1
      - zoo2
      - zoo3
    environment:
      JMX_PORT: 9999
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.32.2:9092    ## 宿主机IP
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2888,zoo3:3888"
    volumes:
      - "./kafka/kafka1/data/:/kafka"


  kafka2:
    image: wurstmeister/kafka
    restart: unless-stopped
    container_name: kafka2
    hostname: kafka2
    expose:
      - "9998"
    ports:
      - "9093:9092"
      - "9998:9998"
    external_links:
      - zoo1
      - zoo2
      - zoo3
    environment:
      JMX_PORT: 9998
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.32.2:9093    ## 宿主机IP
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2888,zoo3:3888"
    volumes:
      - "./kafka/kafka2/data/:/kafka"

  kafka3:
    image: wurstmeister/kafka
    restart: unless-stopped
    container_name: kafka3
    hostname: kafka3
    expose:
      - "9997"
    ports:
      - "9094:9092"
      - "9997:9997"
    external_links:
      - zoo1
      - zoo2
      - zoo3
    environment:
      JMX_PORT: 9997
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.32.2:9094   ## 宿主机IP
      KAFKA_ADVERTISED_HOST_NAME: kafka3
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2888,zoo3:3888"
    volumes:
      - "./kafka/kafka3/data/:/kafka"

  kafka-manager: # Kafka 图形管理界面
    image: hlebalbau/kafka-manager:3.0.0.5
    restart: unless-stopped
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
      - "9000:9000"
    links:            # 连接本compose文件创建的container
      - kafka1
      - kafka2
      - kafka3
    external_links:   # 连接外部compose文件创建的container
      - zoo1
      - zoo2
      - zoo3
    environment:
      ZK_HOSTS: zoo1:2181,zoo2:2888,zoo3:3888
      KAFKA_BROKERS: kafka1:9092,kafka2:9093,kafka3:9094

