version: '3.7'

services:
  influxdb:
    image: influxdb:1.6.4
    container_name: influxdb1.6.4
    restart: always
    environment:
      - PRE_CREATE_DB=mes
      - ADMIN_USER="admin"
      - INFLUXDB_INIT_PWD="admin"
      - GOGC=10
      - INFLUXDB_DATA_INDEX_VERSION=tsi1
    ports:
      - "8086:8086"
    volumes:
      - "./data:/var/lib/influxdb"