version: "3.5"

services:
  mongo:
    container_name: mongo4
    image: mongo:4
    restart: always
    privileged: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      TZ: Asia/Shanghai
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
